// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB29dBZvfepem4H1Ats2qttELz2K8pYV3w',
    appId: '1:826855240062:web:6903d6e296941f0bda432f',
    messagingSenderId: '826855240062',
    projectId: 'servizo-f6131',
    authDomain: 'servizo-f6131.firebaseapp.com',
    storageBucket: 'servizo-f6131.firebasestorage.app',
    measurementId: 'G-L1ETP8V67B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRVaagPLni9Zx_RZwufvdPFh5QlNgx5MI',
    appId: '1:826855240062:android:6963743e05e02550da432f',
    messagingSenderId: '826855240062',
    projectId: 'servizo-f6131',
    storageBucket: 'servizo-f6131.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsRumqoqwCchvOvGpetpbWQZD3w2xhDpY',
    appId: '1:826855240062:ios:38293b7a76053673da432f',
    messagingSenderId: '826855240062',
    projectId: 'servizo-f6131',
    storageBucket: 'servizo-f6131.firebasestorage.app',
    iosBundleId: 'com.example.servizo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsRumqoqwCchvOvGpetpbWQZD3w2xhDpY',
    appId: '1:826855240062:ios:38293b7a76053673da432f',
    messagingSenderId: '826855240062',
    projectId: 'servizo-f6131',
    storageBucket: 'servizo-f6131.firebasestorage.app',
    iosBundleId: 'com.example.servizo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB29dBZvfepem4H1Ats2qttELz2K8pYV3w',
    appId: '1:826855240062:web:e5eaa361c5b07666da432f',
    messagingSenderId: '826855240062',
    projectId: 'servizo-f6131',
    authDomain: 'servizo-f6131.firebaseapp.com',
    storageBucket: 'servizo-f6131.firebasestorage.app',
    measurementId: 'G-XTMFV0EEGM',
  );
}
